# Generated by Django 5.0.7 on 2024-11-28 11:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location='media/images'), upload_to='cottage_images/'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location='media/images'), upload_to='lodge_images/'),
        ),
    ]
