# Generated by Django 5.0.7 on 2024-12-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_mobile',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='object_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.customeraccount'),
            preserve_default=False,
        ),
    ]
