# Generated by Django 5.0.7 on 2024-12-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payroll_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=50),
        ),
    ]
