# Generated by Django 5.1.3 on 2024-12-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payroll_temp_total_hours_alter_payroll_cash_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='temp_total_hours',
        ),
    ]
