# Generated by Django 5.1.2 on 2024-12-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payroll_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acquisitionCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
