# Generated by Django 5.0.7 on 2024-11-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cottage_image_alter_lodge_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='time_12hrs_price',
            new_name='time_6pm_6am_price',
        ),
    ]
