# Generated by Django 5.0.7 on 2024-11-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
