# Generated by Django 5.1.3 on 2024-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_payroll_cash_advance_alter_payroll_deductions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='cash_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
