# Generated by Django 5.0.7 on 2025-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payrolllist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Waiting for Payment', 'Waiting for Payment')], default='Pending', max_length=50),
        ),
    ]
