# Generated by Django 5.1.3 on 2025-01-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payrolllist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='cash_advance',
        ),
    ]
