# Generated by Django 5.0.7 on 2024-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Attendance', 'Attendance'), ('Payroll', 'Payroll'), ('Report', 'Report'), ('Inventory', 'Inventoy'), ('Booking', 'Booking')], max_length=50),
        ),
    ]
