# Generated by Django 5.0.7 on 2024-11-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_auditlog_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
