# Generated by Django 5.0.7 on 2025-01-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservation_payment_deadline_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='cash_advance',
        ),
    ]
