# Generated by Django 5.0.7 on 2024-12-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_payroll_unique_together_cottage_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cottage',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='lodge',
            unique_together={('name', 'type')},
        ),
    ]
