# Generated by Django 5.1.3 on 2025-01-05 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_payroll_cash_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='last_deduction_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
