# Generated by Django 5.1.2 on 2024-12-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
