# Generated by Django 5.0.7 on 2024-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cottage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cottage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lodge',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='name',
            field=models.CharField(default='Unnamed Cottage', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='name',
            field=models.CharField(default='Unnamed Lodge', max_length=255, unique=True),
        ),
    ]
