# Generated by Django 5.0.7 on 2024-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
