# Generated by Django 5.0.7 on 2024-12-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_payroll_unique_together_alter_payroll_employee_and_more'),
        ('api', '0007_alter_cottage_unique_together_and_more'),
    ]

    operations = [
    ]
