# Generated by Django 5.0.7 on 2024-11-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_log_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='category',
        ),
    ]
