# Generated by Django 5.0.7 on 2024-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20241202_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='time_24hrs_price',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='time_6am_12mn_price',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='time_6am_6pm_price',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='time_6pm_6am_price',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='time_12hrs_price',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='time_24hrs_price',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='time_3hrs_price',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='time_6hrs_price',
        ),
        migrations.AddField(
            model_name='cottage',
            name='custom_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='lodge',
            name='custom_prices',
            field=models.JSONField(default=dict),
        ),
    ]
