# Generated by Django 5.0.7 on 2024-11-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_log_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('Employee Registration', 'Employee Registration'), ('Attendance', 'Attendance'), ('Payroll', 'Payroll'), ('Report', 'Report'), ('Inventory', 'Inventory'), ('Booking', 'Booking'), ('System', 'System')], default='System', max_length=50),
        ),
    ]
