# Generated by Django 5.0.7 on 2024-12-03 18:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customprice_remove_cottage_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPrice',
        ),
        migrations.AddField(
            model_name='cottage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location='media/images'), upload_to='cottage_images/'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='custom_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='name',
            field=models.CharField(default='Unnamed Cottage', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
