# Generated by Django 5.0.7 on 2024-12-04 07:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_customprice_cottage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location='media/images'), upload_to='lodge_images/'),
        ),
    ]
