# Generated by Django 5.0.7 on 2024-11-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
