# Generated by Django 5.1.3 on 2024-12-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_lodge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
