# Generated by Django 5.0.7 on 2024-12-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_employee_biometric_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
