# Generated by Django 5.0.7 on 2024-11-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_employeeschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
