# Generated by Django 5.0.7 on 2024-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cottage_lodge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='time',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='time',
        ),
        migrations.AddField(
            model_name='cottage',
            name='time_12hrs_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cottage',
            name='time_24hrs_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cottage',
            name='time_6am_12mn_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cottage',
            name='time_6am_6pm_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lodge',
            name='time_12hrs_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lodge',
            name='time_24hrs_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lodge',
            name='time_3hrs_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lodge',
            name='time_6hrs_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
